"""empty message

Revision ID: 6259ef4c6159
Revises: 7d098cad7439
Create Date: 2021-05-19 15:40:08.785841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6259ef4c6159'
down_revision = '7d098cad7439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('done', sa.Boolean(create_constraint=False), nullable=False))
    op.add_column('todo', sa.Column('tag', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'tag')
    op.drop_column('todo', 'done')
    # ### end Alembic commands ###
